### ISSUE TITLE
Research if we can execute only circuits on AWS simulator

### ISSUE THREAD

**Issue by BonnetGa** [SeQuenC-Consortium/qunicorn-core#105]
## Problem Statement

Currently we only execute circuits on the AWS simulator.
But to execute circuits on the real quantum computers of aws (What we can not do, because it costs), 
we can deploy container to be executed.
So we want to find out, if this is also possible on the simulator.

## Expected Behaviour

Research and test if we can give the local AWS simulator python files or even docker container that will be executed.

## Tasks

- [x] Check if python files can be executed on aws
- [x] Check if Container can be uploaded to the local simulator

**Comment by KuhnMn** [comment]
Sadly, both execution types need a AwsQuantumTask or AwsLocalTask, which only work with AWS credentials
