### ISSUE TITLE
Automate publishing the latest image of a release to ghcr

### ISSUE THREAD

**Issue by GeorgDaniel** [SeQuenC-Consortium/qunicorn-core#11]
### Depends on SeQuenC-Consortium/qunicorn-core#9 

---

Integrate dockerhub into the github releases following:

[https://docs.docker.com/docker-hub/builds/link-source/](https://docs.docker.com/docker-hub/builds/link-source/)

---

Instead of dockerhub, the githubcontainer registry should be used.

- [x] Automated build of every release
- [x] Update docker-compose to use the image in ghcr

**Comment by st161630** [comment]
![Image](https://github.com/SeQuenC-Consortium/qunicorn-core/assets/131953636/a61c9504-a5bc-4627-933f-4ae9775ec875)

Moved to on pending - requires a paid account
