### ISSUE TITLE
Include the Qunicorn logo in rtd

### ISSUE THREAD

**Issue by GeorgDaniel** [SeQuenC-Consortium/qunicorn-core#12]
Upload the Qunicorn Logo and include it as logo in the readthedocs in `docs`

**Comment by st161630** [comment]
- Email to receive Logo File send 
- Created Branch in Main to update Logo quickly

**Comment by st161630** [comment]
- Low quality logo from powerpoint presentation added

**Comment by BonnetGa** [comment]
Logo in den Image Ordner
