### ISSUE TITLE
Visualize Transpile Manager

### ISSUE THREAD

**Issue by st161630** [SeQuenC-Consortium/qunicorn-core#135]
## Problem Statement

We want to visualize the connections between the different languages supported by the transpile manager.
To be discussed if this is done by hand or with automatic generation.

## Expected Behaviour

Have a visualized transpile manager

## Tasks

- [x] Create Graphic

**Comment by wiomoc** [comment]
See https://qiskit.org/ecosystem/rustworkx/dev/apiref/rustworkx.visualization.graphviz_draw.html
