### ISSUE TITLE
Implement REST-design for requests and responses 

### ISSUE THREAD

**Issue by GeorgDaniel** [SeQuenC-Consortium/qunicorn-core#14]
**Context**
HTTP Verbs POST and GET have a meaning in the context of APIs. 

**Next Steps**
- [ ] Familiarize yourself with the CRUD-Method and what the reponse codes 2XX, 3XX, 4XX, 5XX... mean.

Responses to requests should have fitting and detailed response codes

--- 
To be used for
- [ ] SeQuenC-Consortium/qunicorn-core#13 
- [ ] SeQuenC-Consortium/qunicorn-core#8

**Comment by PatrickEbner** [comment]
Already done in #8
