### ISSUE TITLE
Add return message when Job is not existing

### ISSUE THREAD

**Issue by st162107** [SeQuenC-Consortium/qunicorn-core#168]
## Problem Statement

When calling a Job that does not exist (any more) we currently get an AttributeError that the object couldn't be found.

Error that is thrown:
_Error: INTERNAL SERVER ERROR Response body  {   "code": 500,   "error": "AttributeError",   "message": "'NoneType' object has no attribute 'executed_by'" }_

## Expected Behaviour

We want to get an error message that the asked job is not found so the user know that the job is not there any more.

## Tasks

- [ ] Add return of error message when job id is not found

**Comment by st161630** [comment]
Change Error Code to 404
