### ISSUE TITLE
Initial documentation of the project's structure

### ISSUE THREAD

**Issue by v-yussupov** [SeQuenC-Consortium/qunicorn-core#18]
The project should be well documented including its architecture.

- [x] Familiarize yourself with the initial project structure
- [x] Update readthedocs to reflect the current project structure
- [x] Document initial architecture

An example documentation structure can be found [here](https://mico-docs.readthedocs.io/en/latest/index.html).

**Comment by ArneBartenbach** [comment]
Architecture model is added, but further detailed descriptions to each component should be added in the future.

During Setting up "ReadTheDocs" for this fork a Bug has been found that existed before project start and the faulty part is just commented out. A bug ticket has been created: #26

**Comment by BonnetGa** [comment]
PR erstellen

**Comment by obstjn** [comment]
Related PR https://github.com/qunicorn/qunicorn-core/pull/6
