### ISSUE TITLE
CI/CD via GitHub Workflows

### ISSUE THREAD

**Issue by v-yussupov** [SeQuenC-Consortium/qunicorn-core#19]
## Context
GitHub lets you create workflows to setup CI/CD with [GitHub Actions](https://docs.github.com/de/actions).

## Problem/Idea
As a Developer I want to ensure that the code changes work when they are integrated. 

## Requirements
Add GitHub workflow that
- [x] "compiles" the Qunicorn code
- [x] performs linter and formatting checks
- [x] runs tests, and checks that it’s still functional. (depends on #21)

**Comment by st161630** [comment]
Add some basic documentation in confluence for better reproducibility
