### ISSUE TITLE
Setup testing framework

### ISSUE THREAD

**Issue by obstjn** [SeQuenC-Consortium/qunicorn-core#21]
## Context
Flask provides utilities for testing an application [(Flask Documentation)](https://flask.palletsprojects.com/en/2.3.x/testing/).

## Problem
As a Developer I want to ensure that the code changes don't break existing functionalities.
Ensure this by setting up a testing framework focusing on unit tests.

## Requirements
- [x] add `qunicorn_core/tests/` 
- [x] create a dummy unit test serving as an example/template for future test

**Comment by KuhnMn** [comment]
Solved as part of #19
