### ISSUE TITLE
Hex to Bin method for result

### ISSUE THREAD

**Issue by GeorgDaniel** [SeQuenC-Consortium/qunicorn-core#237]
### Context

Output of Qunicorn at the moment is using hex:counts and should be adjusted to bin:counts in order to pass the tests in the qasm test suite

### Tasks

- [x] Implement a hextoBin method
- [x] Test the method with the qasm test suite

### Notes

The convention will be the standard Qiskit / expected outputs in the Testsuite

**Comment by PhilWun** [comment]
Superseded by new result format
