### ISSUE TITLE
REGISTER

### ISSUE THREAD

**Issue by GeorgDaniel** [SeQuenC-Consortium/qunicorn-core#3]
## Features
Qunicorn should be able to save programs/jobs such that they can be executed later/again.

## Overall Requirements

- [x] The unification layer must be able to store pre-deployed job definitions
- [x] Pre-defined quantum circuits and parameters
- [ ] Program files and metadata files
- [ ] Container images

**Comment by obstjn** [comment]
This issue needs further refinement.
