### ISSUE TITLE
Change Qunicorn Logo in readthedocs to svg

### ISSUE THREAD

**Issue by obstjn** [SeQuenC-Consortium/qunicorn-core#43]
If possible use `qunicorn_vertivcal.svg` instead of `.png`.
Probably just need to change https://github.com/SeQuenC-Consortium/qunicorn-core/blob/89edcd46901e38f2686bc89b869602c8106a44b6/docs/conf.py#L202

**Comment by st161630** [comment]
SVGs do not get properly rendered with sphinx_rtd_theme, staying with png for now
