### ISSUE TITLE
Find a general circuit-format that is supported by IBM and AWS for QASM

### ISSUE THREAD

**Issue by BonnetGa** [SeQuenC-Consortium/qunicorn-core#90]
## Problem Statement
Currently we have a QASM3 String for AWS and a QASM2.0 String for IBM.
IBM does support QASM3 but it is not possible to use the string from AWS or wise versa.
We should have one general QASM 3 String that works for IBM and for AWS.

## Tasks
- [ ] Execute a qasm3 String on IBm and on AWS
- [ ] Execute a qasm2 String on IBM and on AWS

**Comment by st161630** [comment]
This Issue will be discussed during a meeting regardings the transpilation between languages. Thus it can be considered finished
