### ISSUE TITLE
Refactor API Endpoints

### ISSUE THREAD

**Issue by GeorgDaniel** [SeQuenC-Consortium/qunicorn-core#92]
## Problem Statement

Ambigous allocation of the resource /jobs

![image](https://github.com/SeQuenC-Consortium/qunicorn-core/assets/56876774/b54fba1f-7cc0-4a63-9a64-431fcf72557d)

![image](https://github.com/SeQuenC-Consortium/qunicorn-core/assets/56876774/0620a42d-74bd-4cbf-a467-be31abba812e)

If `Job_ID == Deployment_ID`, then both operate on e.g. `http://localhost:5005/jobs/1/`

## Expected Behavior

Functionality should be the same, but under `deployments/{deployment_id}/jobs`

## Tasks

- [x] Refactor both API endpoints
- [x] Test the functionality

## Notes

Should be very fast for Team 1, but very good first issue for Team 2

**Comment by st161630** [comment]
In die Deployment API
